{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenC-CNN",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOpenC-CNN-1.0.aar",
          "url": "libOpenC-CNN-1.0.aar",
          "size": 122607,
          "sha512": "ab13cf4323b06fa275087626e0471f2fc70fa0c3289fd9b6849858b5e6cd54851c3069e87b1e6463c46d53d5ca162769c172e79d65e2df914c0e750c21b08561",
          "sha256": "98f9563c8336cb9fc83a8e47caa2f7d1339bba1233671b33729314cc57c5b60a",
          "sha1": "771f9b6c1ef9683edaa72460ffb79350907b9054",
          "md5": "b17aaaf11de922389154012ed185105c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenC-CNN-1.0.aar",
          "url": "libOpenC-CNN-1.0.aar",
          "size": 122607,
          "sha512": "ab13cf4323b06fa275087626e0471f2fc70fa0c3289fd9b6849858b5e6cd54851c3069e87b1e6463c46d53d5ca162769c172e79d65e2df914c0e750c21b08561",
          "sha256": "98f9563c8336cb9fc83a8e47caa2f7d1339bba1233671b33729314cc57c5b60a",
          "sha1": "771f9b6c1ef9683edaa72460ffb79350907b9054",
          "md5": "b17aaaf11de922389154012ed185105c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libOpenC-CNN-1.0-sources.jar",
          "url": "libOpenC-CNN-1.0-sources.jar",
          "size": 1022,
          "sha512": "8eadc17a4854e8b5be93357fe2a590a649e2e9d71c4aa06b7726773c920c1bc878e635d13b3d6828f64eb1bf445f087629d589b80f8d3ca7c4ed4c638de9a4cf",
          "sha256": "6d87eee9b73eb18c413970078766fde1334960e7858a7b5350bb47cecc597901",
          "sha1": "8459b21af065a943369a8c77ffff1bae489bc099",
          "md5": "33ed9c3820e7ff275a672e26a9fb9e23"
        }
      ]
    }
  ]
}
