{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libSessionUtils",
    "version": "2.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.3.aar",
          "url": "libSessionUtils-2.9.3.aar",
          "size": 195256,
          "sha512": "378dbb7f50fe56c9eafbfdc96f176ddfa4cf09881d2c3c95ca6159990972ecce8936f8e59c7f81d85711002abc92029b0ee396ee426689c8d7ddbd8c5bcc59ad",
          "sha256": "795f3fa4f7a51355f3fec48ad30e2a046f85f19aa91fcf9648a503e0e1d0f6e4",
          "sha1": "70108bd657d1934afaa4268698dcc0bec8a648da",
          "md5": "9b1eb6d2c3cf2f0972aba189ae471e6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXMediaUtils",
          "version": {
            "requires": "2.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXPlayerUtils",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFPersistUtils",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "libSessionUtils-2.9.3.aar",
          "url": "libSessionUtils-2.9.3.aar",
          "size": 195256,
          "sha512": "378dbb7f50fe56c9eafbfdc96f176ddfa4cf09881d2c3c95ca6159990972ecce8936f8e59c7f81d85711002abc92029b0ee396ee426689c8d7ddbd8c5bcc59ad",
          "sha256": "795f3fa4f7a51355f3fec48ad30e2a046f85f19aa91fcf9648a503e0e1d0f6e4",
          "sha1": "70108bd657d1934afaa4268698dcc0bec8a648da",
          "md5": "9b1eb6d2c3cf2f0972aba189ae471e6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libSessionUtils-2.9.3-sources.jar",
          "url": "libSessionUtils-2.9.3-sources.jar",
          "size": 85771,
          "sha512": "b0bf488d271d0416c3b7efcbf0c72adc1439f5e8848446130e18c0ad1aa5e7a06ebc26462eb3b449bd1a681b9b9c9f22259c872c8ad90ced85e3a0f648ca4fcd",
          "sha256": "3f1dd07473a37ae0e99e6de6e22c87fbab91810d9799d8cb7060cff6572f8d4c",
          "sha1": "1055c7c9f1d46810c6ee19c10f83898d13a50d6c",
          "md5": "319825555eeaac49b2851f9c12a75bf7"
        }
      ]
    }
  ]
}
