{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFOSUtils",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.2.aar",
          "url": "libFOSUtils-1.4.2.aar",
          "size": 208520,
          "sha512": "c9c6db52af35870ccc0582f12218a79576e32be066b24d098db48c330228385b36971cfe80e3fbe51ac3e6a79ee170f1f539777dc958863db241bce3371706e8",
          "sha256": "bd993960499db15b94adbe43a2db8a3a6dc373497d265d014804e185a94a021c",
          "sha1": "049fb753f4f4c3852a7b5abc7d576ea90b1a814a",
          "md5": "069e2e4048d2e8ccf8d2d887728ddb6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "libFOSUtils-1.4.2.aar",
          "url": "libFOSUtils-1.4.2.aar",
          "size": 208520,
          "sha512": "c9c6db52af35870ccc0582f12218a79576e32be066b24d098db48c330228385b36971cfe80e3fbe51ac3e6a79ee170f1f539777dc958863db241bce3371706e8",
          "sha256": "bd993960499db15b94adbe43a2db8a3a6dc373497d265d014804e185a94a021c",
          "sha1": "049fb753f4f4c3852a7b5abc7d576ea90b1a814a",
          "md5": "069e2e4048d2e8ccf8d2d887728ddb6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libFOSUtils-1.4.2-sources.jar",
          "url": "libFOSUtils-1.4.2-sources.jar",
          "size": 77386,
          "sha512": "5e34402f9a30e8a1a5a083e3f22bb0b35d4fefe178a2808b635e05a4eff71bc031e88d955445b01b6f41497df9f0a5b2252dc83f0f71b20223d4e06c3d326c79",
          "sha256": "de4faeb8337c8cc0217ef489bb080359971315872e4f14e5aeaa2e7616125a4c",
          "sha1": "d263b4627a8de5a2c716368e050fc9eaf4fac79e",
          "md5": "5746b9bf398202d08f68101cc3282b90"
        }
      ]
    }
  ]
}
