{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libDNetUtils",
    "version": "2.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libDNetUtils-2.1.1.aar",
          "url": "libDNetUtils-2.1.1.aar",
          "size": 38127,
          "sha512": "bc3804972bbdb2071a223bdecd7964c57b555216b2fe90ae941a6e8b140f529f4f4c497c308377b08253e5bc35466af8e555ee3848db8199be8c2c46b904f741",
          "sha256": "3ac0216fcdb0d62f21c305a1557b43719d24f14af1f8f64fe184719840a73e2d",
          "sha1": "2a349f95eb0fa98d5fdc40c4d585c0366f216430",
          "md5": "9f78975977aee757ee7b02d875c868fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "libDNetUtils-2.1.1.aar",
          "url": "libDNetUtils-2.1.1.aar",
          "size": 38127,
          "sha512": "bc3804972bbdb2071a223bdecd7964c57b555216b2fe90ae941a6e8b140f529f4f4c497c308377b08253e5bc35466af8e555ee3848db8199be8c2c46b904f741",
          "sha256": "3ac0216fcdb0d62f21c305a1557b43719d24f14af1f8f64fe184719840a73e2d",
          "sha1": "2a349f95eb0fa98d5fdc40c4d585c0366f216430",
          "md5": "9f78975977aee757ee7b02d875c868fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libDNetUtils-2.1.1-sources.jar",
          "url": "libDNetUtils-2.1.1-sources.jar",
          "size": 15071,
          "sha512": "91d53d84ea64229357f14e16fa65ab6ce5d15c8465835d30293a125465abc1b85c0f03170c713257245ce36f7476886fccc24d360800ee1ce790c5fdf3a74822",
          "sha256": "2e5ba28de8733f7eade33f70b218bb5ecd1945e44b963351618e9d85e9513023",
          "sha1": "1e2e0a11a7b33c1ec38264e487a948ef6b3fed84",
          "md5": "92af330865b8957ed4826f4472ade6be"
        }
      ]
    }
  ]
}
