{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenIPC-OTMS",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOpenIPC-OTMS-1.0.0.aar",
          "url": "libOpenIPC-OTMS-1.0.0.aar",
          "size": 2514856,
          "sha512": "47e9cd376b57610fdcd209c685748c272640a154373a43a8dbb6bb044a2bf0cc51b336eacb8c5bb9ef5bbf37b6d87384e88064ab5fbb4686a63d7bd6491896c8",
          "sha256": "1b29be81e48b16bb492cfcdd1b5b0703ec0b3a5af997f7b32a245f2f859a3a07",
          "sha1": "f0b4f154e0d08d5384a744e1f1ba960d3148bb20",
          "md5": "7d5d1bb544524868dad3820524b40d3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.20"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenIPC-OTMS-1.0.0.aar",
          "url": "libOpenIPC-OTMS-1.0.0.aar",
          "size": 2514856,
          "sha512": "47e9cd376b57610fdcd209c685748c272640a154373a43a8dbb6bb044a2bf0cc51b336eacb8c5bb9ef5bbf37b6d87384e88064ab5fbb4686a63d7bd6491896c8",
          "sha256": "1b29be81e48b16bb492cfcdd1b5b0703ec0b3a5af997f7b32a245f2f859a3a07",
          "sha1": "f0b4f154e0d08d5384a744e1f1ba960d3148bb20",
          "md5": "7d5d1bb544524868dad3820524b40d3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libOpenIPC-OTMS-1.0.0-sources.jar",
          "url": "libOpenIPC-OTMS-1.0.0-sources.jar",
          "size": 1534,
          "sha512": "07e6f6419cdc7361cecae43608a2ec5213b54d46737068fb18abf9fa18c8a15f1c8fe066dcc9db4a8a6eb77a0b4c77a400a56677ee62db29489ada26c9413fe0",
          "sha256": "14bd8614736d01d024015d69238da1742a28a9a6a2205dcf177748477cf599b8",
          "sha1": "e225285c4e86586b82d7860a1376628026d36bd8",
          "md5": "6c165edd67cd4a04100e73483996affc"
        }
      ]
    }
  ]
}
