{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libGXMediaUtils",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libGXMediaUtils-2.0.aar",
          "url": "libGXMediaUtils-2.0.aar",
          "size": 26326,
          "sha512": "651fbaf5e8c96c11bced41d86162f621c4ea1a1cbe69771b37597f8eaecf0074393f47161283a6004bc06220e5e12b6f03324694bdbc7b8e5c889a96c006bfd8",
          "sha256": "6afc2ca5023a9f0decc6953c320304b6215fd02d1bd00f272132469b0af18172",
          "sha1": "6d60da139e291a5677a21e6e5937e9c4e8c6f1ce",
          "md5": "b48b55bf71caa97d1eaf0b84f86cce51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFPersistUtils",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXPlayerUtils",
          "version": {
            "requires": "3.0"
          }
        }
      ],
      "files": [
        {
          "name": "libGXMediaUtils-2.0.aar",
          "url": "libGXMediaUtils-2.0.aar",
          "size": 26326,
          "sha512": "651fbaf5e8c96c11bced41d86162f621c4ea1a1cbe69771b37597f8eaecf0074393f47161283a6004bc06220e5e12b6f03324694bdbc7b8e5c889a96c006bfd8",
          "sha256": "6afc2ca5023a9f0decc6953c320304b6215fd02d1bd00f272132469b0af18172",
          "sha1": "6d60da139e291a5677a21e6e5937e9c4e8c6f1ce",
          "md5": "b48b55bf71caa97d1eaf0b84f86cce51"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libGXMediaUtils-2.0-sources.jar",
          "url": "libGXMediaUtils-2.0-sources.jar",
          "size": 13577,
          "sha512": "a63884cabfa3ef454ffd283f10514ee3843dff4cb59765b721830133a02a5653a409e14eb9077cafb65d2b5337b6b198f06e14b2646b9602c7dce6fad8ba8362",
          "sha256": "6460b1a735dd1f289bbdf89beb9a3e99afe8fa483b0b3b67b3e3563ec8d5d42e",
          "sha1": "27c11dfb6e630a3036cbb744cc93ddd9d4e3c33f",
          "md5": "ca3116813faa28cd499bcc521c01adea"
        }
      ]
    }
  ]
}
