{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libGXMediaUtils",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libGXMediaUtils-2.0.aar",
          "url": "libGXMediaUtils-2.0.aar",
          "size": 26013,
          "sha512": "a901f5e44fc03db8917e697e77e488c6e3772321bb78c01ad79a170e4751cabb8cbc9b8a8038432b92eb6658daf6ece617b2cf98a27e541a390c4e41712d1e41",
          "sha256": "2eaa8ced60ee49d61b4953e28e343a5615a1c99bc800e30b8db09513cb031d5f",
          "sha1": "7003e0ec7caf3b35c817f85a0f966c129fbd1081",
          "md5": "31e4072590c31ebbf32d215915d97077"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFPersistUtils",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libGXPlayerUtils",
          "version": {
            "requires": "3.0"
          }
        }
      ],
      "files": [
        {
          "name": "libGXMediaUtils-2.0.aar",
          "url": "libGXMediaUtils-2.0.aar",
          "size": 26013,
          "sha512": "a901f5e44fc03db8917e697e77e488c6e3772321bb78c01ad79a170e4751cabb8cbc9b8a8038432b92eb6658daf6ece617b2cf98a27e541a390c4e41712d1e41",
          "sha256": "2eaa8ced60ee49d61b4953e28e343a5615a1c99bc800e30b8db09513cb031d5f",
          "sha1": "7003e0ec7caf3b35c817f85a0f966c129fbd1081",
          "md5": "31e4072590c31ebbf32d215915d97077"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libGXMediaUtils-2.0-sources.jar",
          "url": "libGXMediaUtils-2.0-sources.jar",
          "size": 13226,
          "sha512": "b4ee19a8294b43f720ac9f082e310dea252fe31635d2852d75be6debd2f89b71d09a41a70635b455f63a88fa17593e86455d75b6d848f5d9f8eed179755d27ef",
          "sha256": "056bc58e549a94811c60a4ac13dc15d9451765993fddcc4627603173dad3afb8",
          "sha1": "05bad951f2688609fb432830d32bc9b1ebc2d15d",
          "md5": "992352c11c9a2908b1257da56eeeba4d"
        }
      ]
    }
  ]
}
