{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenLargeModelDeepLearning",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libOpenLargeModelDeepLearning-1.0.aar",
          "url": "libOpenLargeModelDeepLearning-1.0.aar",
          "size": 2096740,
          "sha512": "64a46acb36c9890e25732fce5684e1b2babf8e6aef4573a4f4b1b502a7a47c0d4e778c410b2d1378df2d9aaa90cdda31b2ea391395950dfeca994dddc45e1ef7",
          "sha256": "f8c1c3a52c53782284d019f7e66f215d15aafb5b200ddbe84f394cae132b7bae",
          "sha1": "4f653407096c53d99c40a24ad12f147b3a50763e",
          "md5": "0a09df9e7802f639fa80ab4cfff009f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libOpenComputerVision",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenLargeModelDeepLearning-1.0.aar",
          "url": "libOpenLargeModelDeepLearning-1.0.aar",
          "size": 2096740,
          "sha512": "64a46acb36c9890e25732fce5684e1b2babf8e6aef4573a4f4b1b502a7a47c0d4e778c410b2d1378df2d9aaa90cdda31b2ea391395950dfeca994dddc45e1ef7",
          "sha256": "f8c1c3a52c53782284d019f7e66f215d15aafb5b200ddbe84f394cae132b7bae",
          "sha1": "4f653407096c53d99c40a24ad12f147b3a50763e",
          "md5": "0a09df9e7802f639fa80ab4cfff009f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libOpenLargeModelDeepLearning-1.0-sources.jar",
          "url": "libOpenLargeModelDeepLearning-1.0-sources.jar",
          "size": 1062,
          "sha512": "6d4fd93729c7c3994432bf8379afa031d82464e07dc65eb0e7569b6016a226ff99b25331aab2b105e9c5d495b791f74813582220c02e0abfc5beba84c481e58c",
          "sha256": "20eae7400e96e196374cc00862be9c7a51e5b278aca0d6f503c75cecd5acd126",
          "sha1": "8396d041dacfc0d93ada57d3704a4a4f868748c0",
          "md5": "ca067171fed9e42ab2705a7136af4660"
        }
      ]
    }
  ]
}
