{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libGXPlayerUtils",
    "version": "3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libGXPlayerUtils-3.0.aar",
          "url": "libGXPlayerUtils-3.0.aar",
          "size": 206554,
          "sha512": "190d5ccb5f96ee353b02a56e7cc836bc267b3da8b8adf41a150811fb862f37109a23dd7230bf0a7fec0de996f5caeb7d5cc33b337e7818e1af07d97496371770",
          "sha256": "a0deb8157bf114135070fd23842ffa097164e88f136b7c4a26004638607f8c35",
          "sha1": "fcfd43ee2b9d8c9347872f2d9a1b6b3fbebca09b",
          "md5": "c61f82bd509fddbf03ed05026ca33729"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libDNetUtils",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libFOSUtils",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "org.videolan.android",
          "module": "libvlc-all",
          "version": {
            "requires": "4.0.0-eap23"
          }
        }
      ],
      "files": [
        {
          "name": "libGXPlayerUtils-3.0.aar",
          "url": "libGXPlayerUtils-3.0.aar",
          "size": 206554,
          "sha512": "190d5ccb5f96ee353b02a56e7cc836bc267b3da8b8adf41a150811fb862f37109a23dd7230bf0a7fec0de996f5caeb7d5cc33b337e7818e1af07d97496371770",
          "sha256": "a0deb8157bf114135070fd23842ffa097164e88f136b7c4a26004638607f8c35",
          "sha1": "fcfd43ee2b9d8c9347872f2d9a1b6b3fbebca09b",
          "md5": "c61f82bd509fddbf03ed05026ca33729"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libGXPlayerUtils-3.0-sources.jar",
          "url": "libGXPlayerUtils-3.0-sources.jar",
          "size": 20603,
          "sha512": "71c1dfa06a1190fbc38895acc008ffd9aaea32861a3926e5478c6a0385aad6fe233f736ab6536e2012f7a96929e53e36ff404c6fae98a5f97bc39a4280de4737",
          "sha256": "ce68db6013ed7e1c206ebd87a2d533eb3999a46b1db909f6243db567cb2e4279",
          "sha1": "dff1f9a3d7b1fc1b807e46f3cedd316bd5c1e5d6",
          "md5": "f7ff7bfe38122831ae89e44454a20b9a"
        }
      ]
    }
  ]
}
