{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libOpenDetection",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenDetection-1.1.aar",
          "url": "libOpenDetection-1.1.aar",
          "size": 21327,
          "sha512": "9db0e9394ad93ac6a04a345df25a0bf8562e8c46271dac8a721263c13d275250099bf3595aca90dec6ab413da6e33956987994ce30e77e843c5eb0d16ac6cb20",
          "sha256": "5f4e2ea127f080d4a30abf29d3c07a201d1a5e02a4a87c9a9447da41d021e0b5",
          "sha1": "f2475815c1c5f8b9d9e3eee911a7e030f389ae70",
          "md5": "87b083fb4f89b69368f7532b9387f3b9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "com.zhuchao.android",
          "module": "libOpenComputerVision",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-gpu",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "libOpenDetection-1.1.aar",
          "url": "libOpenDetection-1.1.aar",
          "size": 21327,
          "sha512": "9db0e9394ad93ac6a04a345df25a0bf8562e8c46271dac8a721263c13d275250099bf3595aca90dec6ab413da6e33956987994ce30e77e843c5eb0d16ac6cb20",
          "sha256": "5f4e2ea127f080d4a30abf29d3c07a201d1a5e02a4a87c9a9447da41d021e0b5",
          "sha1": "f2475815c1c5f8b9d9e3eee911a7e030f389ae70",
          "md5": "87b083fb4f89b69368f7532b9387f3b9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "libOpenDetection-1.1-sources.jar",
          "url": "libOpenDetection-1.1-sources.jar",
          "size": 15347,
          "sha512": "7c965f2d7628ae1b50f8903dabdf0d2f58f220791cb3656b3cdb304bb62bd42748821ef524abee5c8c24461546d92d4a09620536410d64d9be774a9f1d5f803c",
          "sha256": "32cdf235de7a400cb6d332acce68fb2fc79486e75f38f6745455a19a9672b55b",
          "sha1": "b87baa63e3a969f6c30c79416a264d78b913a4f7",
          "md5": "22b266245465a7f123d0f51fe3ef49f6"
        }
      ]
    }
  ]
}
