{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libBaseUtils",
    "version": "2.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.3.aar",
          "url": "libBaseUtils-2.2.3.aar",
          "size": 119117,
          "sha512": "951f206ca5e05cf4695e91a8503f31d878c7272aa5a68885e6bd7bc96af6220e4a44b1e37944bfedbeadee39bb3d9a08413f16010d0e3a02ea5a0d02fe7af871",
          "sha256": "3b7c230a85245b03c7c2b69947469c3bde4b421738576a1122d5e7356b6bcac4",
          "sha1": "8b4b8973272dd33706b2639c35df4425a9a6ce5a",
          "md5": "4096367224428a377b413fa22a4117c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.20"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.documentfile",
          "module": "documentfile",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.things",
          "module": "androidthings",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "5.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "libBaseUtils-2.2.3.aar",
          "url": "libBaseUtils-2.2.3.aar",
          "size": 119117,
          "sha512": "951f206ca5e05cf4695e91a8503f31d878c7272aa5a68885e6bd7bc96af6220e4a44b1e37944bfedbeadee39bb3d9a08413f16010d0e3a02ea5a0d02fe7af871",
          "sha256": "3b7c230a85245b03c7c2b69947469c3bde4b421738576a1122d5e7356b6bcac4",
          "sha1": "8b4b8973272dd33706b2639c35df4425a9a6ce5a",
          "md5": "4096367224428a377b413fa22a4117c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libBaseUtils-2.2.3-sources.jar",
          "url": "libBaseUtils-2.2.3-sources.jar",
          "size": 69174,
          "sha512": "82b6e175c28838a9c5e2a6a63888f30f04448b7089d78f90beeee50a909d8e9bdeece6f2771bc33ecd82ac93b59f70fc8aa776fa13f6a346f7fa3cbebf633404",
          "sha256": "29676be493a8b186954241cf409409b57a200f16cdb5c0d47444053ac46c0e6f",
          "sha1": "4e171447156ab8136e49e1a099903ac1b0ab020b",
          "md5": "b411d0d10a2b4846921a701bd3c462d9"
        }
      ]
    }
  ]
}
