{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libFPersistUtils",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "libFPersistUtils-1.2.aar",
          "url": "libFPersistUtils-1.2.aar",
          "size": 9701,
          "sha512": "5ccb0c5ec2d67112b5f4c48fee8652fd42f1a9e2d9467987e39c9c579865c8c83c877f2cb978f80e8c6a90af6312d8ecda586b15b0ad87a8082efb98a297c1ee",
          "sha256": "15d71f532a5f9ab36619dfd6232c3082498081f7eb1fb1f4d7224945b5d7c6c8",
          "sha1": "1357d5902de29778132bb6f65ef1908353273690",
          "md5": "eda90c977ccb1bc122c136495a62b808"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "libFPersistUtils-1.2.aar",
          "url": "libFPersistUtils-1.2.aar",
          "size": 9701,
          "sha512": "5ccb0c5ec2d67112b5f4c48fee8652fd42f1a9e2d9467987e39c9c579865c8c83c877f2cb978f80e8c6a90af6312d8ecda586b15b0ad87a8082efb98a297c1ee",
          "sha256": "15d71f532a5f9ab36619dfd6232c3082498081f7eb1fb1f4d7224945b5d7c6c8",
          "sha1": "1357d5902de29778132bb6f65ef1908353273690",
          "md5": "eda90c977ccb1bc122c136495a62b808"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "libFPersistUtils-1.2-sources.jar",
          "url": "libFPersistUtils-1.2-sources.jar",
          "size": 13243,
          "sha512": "8ba46e05b42817055d2560315cf24a086624b7d8dcea3bb4e2452c66388e608e00c199fe93a55c802beceb69d7f1d42e37c8506110ce1a7d4566bd6355b445be",
          "sha256": "dacaf986bf40dd92de55433c64f591ce203586bdcd062f1b81d2aa27179d6fad",
          "sha1": "901aaefcb26387c486d13689421d2dcf806e086e",
          "md5": "b4a3fbe3faf2b251ce2c61aca6c72e3b"
        }
      ]
    }
  ]
}
