{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhuchao.android",
    "module": "libCameraUtils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libCameraUtils-1.0.aar",
          "url": "libCameraUtils-1.0.aar",
          "size": 28230,
          "sha512": "a63ea11481743e445e81f85b9240534b6883a61f314986e47bbfd71e7728a8e5abf364477204d111b4ba820c0cb2a7dd3dfc9737342f91f70b0885a697470d84",
          "sha256": "98ec6c977b44064f07077ae39b654bfeb56b1016addf6834a9cb9416f522aaf1",
          "sha1": "cdd6530c3b94821c1a30525cfac4b4dc9c954cca",
          "md5": "cecdd7f0ce3da20fcbf0fa46b3c19e86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zhuchao.android",
          "module": "libBaseUtils",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.20"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "libCameraUtils-1.0.aar",
          "url": "libCameraUtils-1.0.aar",
          "size": 28230,
          "sha512": "a63ea11481743e445e81f85b9240534b6883a61f314986e47bbfd71e7728a8e5abf364477204d111b4ba820c0cb2a7dd3dfc9737342f91f70b0885a697470d84",
          "sha256": "98ec6c977b44064f07077ae39b654bfeb56b1016addf6834a9cb9416f522aaf1",
          "sha1": "cdd6530c3b94821c1a30525cfac4b4dc9c954cca",
          "md5": "cecdd7f0ce3da20fcbf0fa46b3c19e86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libCameraUtils-1.0-sources.jar",
          "url": "libCameraUtils-1.0-sources.jar",
          "size": 14168,
          "sha512": "99e7b18ef4abfc4d095ef54d98db46c514246750feb30d5636dc9ebbad1b33319dd796d6ecdceaa250fbe2f5dc56695dc5edb3aa8d2647d0a76db922740e9f34",
          "sha256": "cbe935bb11a5e8d08abff1f7717d1c027c3936eff90de2113d60038195f26a86",
          "sha1": "4014e8a4bf9b40afb412ed79616d49cf19f4f800",
          "md5": "428e17bdad517d8028314a4d22063652"
        }
      ]
    }
  ]
}
